#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import argparse
import subprocess
import time
import os
import sys
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROOT = Path('/home/hy/문서/WMU_project/analysis_basic_v1/analysis_fault_generalization_v1')
MANIFEST = ROOT / 'manifests' / 'fault_generalization_manifest.csv'
RAW = ROOT / 'raw_csv'
LOGDIR = ROOT / 'logs' / 'ieee30_serial_resume'
DIAG = ROOT / 'diagnostics'
MATLAB = '/home/hy/MATLAB_R2024a/bin/matlab'
MATLAB_SCRIPT_DIR = PROJECT_ROOT / 'scripts' / 'matlab'


def validate_csv(path: Path, nbus: int = 30) -> tuple[bool, str]:
    if not path.exists():
        return False, 'missing'
    try:
        header = pd.read_csv(path, nrows=0)
        expected_cols = 1 + nbus * 6
        if len(header.columns) != expected_cols:
            return False, f'columns={len(header.columns)} expected={expected_cols}'
        expected = ['Time'] + [f'{x}_{b}' for b in range(1, nbus + 1) for x in ['Va','Vb','Vc','Ia','Ib','Ic']]
        miss = [c for c in expected if c not in header.columns]
        if miss:
            return False, 'missing_columns=' + ';'.join(miss[:5])
        with path.open('rb') as f:
            rows = sum(1 for _ in f) - 1
        if rows != 10001:
            return False, f'rows={rows} expected=10001'
        df = pd.read_csv(path)
        t = df['Time'].to_numpy(dtype=float)
        if abs(t[0]) > 1e-12 or abs(t[-1] - 0.5) > 1e-9:
            return False, f'time_range={t[0]}..{t[-1]}'
        dt = np.diff(t)
        if not np.all(dt > 0):
            return False, 'time_not_monotonic'
        if np.max(np.abs(dt - 5e-5)) > 1e-9:
            return False, f'bad_dt_maxerr={np.max(np.abs(dt - 5e-5))}'
        arr = df.to_numpy(dtype=float)
        if not np.isfinite(arr).all():
            return False, 'nan_or_inf'
        return True, ''
    except Exception as e:
        return False, type(e).__name__ + ': ' + str(e)[:300]


def load_manifest() -> pd.DataFrame:
    df = pd.read_csv(MANIFEST)
    for col in ['NetworkID', 'FaultType', 'BackgroundName', 'OutputFile', 'Status', 'ErrorMessage']:
        if col in df.columns:
            df[col] = df[col].fillna('').astype(str)
    return df


def sync_manifest(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for i, row in df.iterrows():
        if str(row['NetworkID']) != 'ieee30':
            continue
        ok, msg = validate_csv(Path(str(row['OutputFile'])), 30)
        if ok:
            df.at[i, 'Status'] = 'SUCCESS'
            if pd.isna(df.at[i, 'Runtime']):
                df.at[i, 'Runtime'] = 0
            df.at[i, 'ErrorMessage'] = ''
        elif str(df.at[i, 'Status']) not in ['TIMEOUT', 'FAILED']:
            df.at[i, 'Status'] = 'PENDING'
            df.at[i, 'ErrorMessage'] = msg
    df.to_csv(MANIFEST, index=False)
    return df


def write_pending_diagnostics(df: pd.DataFrame) -> None:
    DIAG.mkdir(parents=True, exist_ok=True)
    ieee30 = df[df['NetworkID'].astype(str) == 'ieee30'].copy()
    rows = []
    for _, r in ieee30.iterrows():
        p = Path(str(r['OutputFile']))
        ok, msg = validate_csv(p, 30)
        base = r.to_dict()
        base['expected output path'] = str(p)
        base['assigned runner subset'] = 'serial_resume'
        base['previous attempt count'] = int((LOGDIR / f"case_{int(r['CaseID']):04d}_attempt1.log").exists()) + int((LOGDIR / f"case_{int(r['CaseID']):04d}_attempt2.log").exists())
        base['last error'] = msg
        base['status'] = 'COMPLETED_VALID' if ok else str(r.get('Status', 'PENDING'))
        rows.append(base)
    allr = pd.DataFrame(rows)
    allr[allr['status'] == 'COMPLETED_VALID'].to_csv(DIAG / 'ieee30_completed_cases.csv', index=False)
    pend = allr[allr['status'] != 'COMPLETED_VALID'].copy()
    pend.to_csv(DIAG / 'ieee30_pending_cases.csv', index=False)
    cands = []
    for _, sub in pend.sort_values('CaseID').groupby('FaultBus'):
        if len(sub): cands.append(sub.iloc[0])
    pr = pend[(pend['FaultResistanceOhm'].astype(float).eq(10)) | (pend['FaultInceptionAngleDeg'].astype(float).eq(90)) | (pend['BackgroundName'].astype(str).eq('SSO25Hz_M03'))].sort_values('CaseID').head(20)
    for _, rr in pr.iterrows(): cands.append(rr)
    stalled = pd.DataFrame(cands).drop_duplicates(subset=['CaseID']) if cands else pend.head(0)
    stalled.to_csv(DIAG / 'ieee30_stalled_case_candidates.csv', index=False)


def cleanup_caches() -> None:
    # Do not delete output CSVs. Only remove model autosave/cache generated by killed MATLAB runs.
    for p in [Path('/home/hy/문서/matlab/Thirtybussys_WMU_IBR_auto.slx.autosave')]:
        try:
            if p.exists():
                backup = DIAG / 'autosave_backup'
                backup.mkdir(exist_ok=True)
                p.rename(backup / f'{p.name}.{int(time.time())}')
        except Exception:
            pass


def run_case(case_id: int, timeout_s: int, attempt: int) -> tuple[str, float, str]:
    LOGDIR.mkdir(parents=True, exist_ok=True)
    log = LOGDIR / f'case_{case_id:04d}_attempt{attempt}.log'
    cmd = [MATLAB, '-batch', f"addpath('{MATLAB_SCRIPT_DIR}'); run_fault_generalization_v1('case_{case_id}')"]
    start = time.time()
    with log.open('w') as f:
        f.write(f'=== start {time.strftime("%Y-%m-%dT%H:%M:%S%z")} case={case_id} attempt={attempt} timeout={timeout_s}\n')
        f.write('cmd=' + ' '.join(cmd) + '\n')
        f.flush()
        try:
            r = subprocess.run(cmd, cwd=PROJECT_ROOT, stdout=f, stderr=subprocess.STDOUT, timeout=timeout_s)
            code = r.returncode
        except subprocess.TimeoutExpired:
            f.write(f'\n=== TIMEOUT after {timeout_s}s ===\n')
            return 'TIMEOUT', time.time() - start, f'timeout after {timeout_s}s; log={log}'
    elapsed = time.time() - start
    if code != 0:
        return 'FAILED', elapsed, f'exit_code={code}; log={log}'
    df = load_manifest()
    row = df[(df['NetworkID'].astype(str) == 'ieee30') & (df['CaseID'].astype(int) == case_id)].iloc[0]
    ok, msg = validate_csv(Path(str(row['OutputFile'])), 30)
    return ('SUCCESS' if ok else 'FAILED'), elapsed, msg + f'; log={log}'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--limit', type=int, default=10)
    ap.add_argument('--timeout', type=int, default=600)
    ap.add_argument('--max-retry', type=int, default=1)
    args = ap.parse_args()
    df = sync_manifest(load_manifest())
    write_pending_diagnostics(df)
    ieee30 = df[df['NetworkID'].astype(str) == 'ieee30'].copy()
    pending = ieee30[ieee30['Status'].astype(str) != 'SUCCESS'].sort_values('CaseID')
    if args.limit > 0:
        pending = pending.head(args.limit)
    start_all = time.time(); done = 0; retries = 0; timeouts = 0; failures = 0; max_elapsed = 0.0
    progress_log = ROOT / 'logs' / 'ieee30_serial_resume_progress.log'
    for _, row in pending.iterrows():
        cid = int(row['CaseID'])
        status = 'FAILED'; msg = '' ; elapsed = 0.0
        for attempt in range(1, args.max_retry + 2):
            cleanup_caches()
            df = load_manifest()
            idx = df[(df['NetworkID'].astype(str) == 'ieee30') & (df['CaseID'].astype(int) == cid)].index[0]
            df.at[idx, 'Status'] = 'RUNNING'; df.at[idx, 'ErrorMessage'] = ''; df.to_csv(MANIFEST, index=False)
            status, elapsed, msg = run_case(cid, args.timeout, attempt)
            max_elapsed = max(max_elapsed, elapsed)
            df = load_manifest()
            idx = df[(df['NetworkID'].astype(str) == 'ieee30') & (df['CaseID'].astype(int) == cid)].index[0]
            df.at[idx, 'Status'] = status
            df.at[idx, 'Runtime'] = elapsed
            df.at[idx, 'ErrorMessage'] = '' if status == 'SUCCESS' else msg
            df.to_csv(MANIFEST, index=False)
            if status == 'SUCCESS':
                break
            if attempt <= args.max_retry:
                retries += 1
                cleanup_caches()
        done += 1
        if status == 'TIMEOUT': timeouts += 1
        if status == 'FAILED': failures += 1
        df = sync_manifest(load_manifest())
        counts = df[df['NetworkID'].astype(str)=='ieee30']['Status'].value_counts().to_dict()
        remaining = int((df[(df['NetworkID'].astype(str)=='ieee30')]['Status'].astype(str) != 'SUCCESS').sum())
        avg = (time.time() - start_all) / done
        with progress_log.open('a') as f:
            f.write(f"{time.strftime('%Y-%m-%dT%H:%M:%S%z')} case={cid} status={status} elapsed={elapsed:.2f} done_this_run={done} remaining={remaining} avg={avg:.2f} max={max_elapsed:.2f} retries={retries} timeouts={timeouts} failures={failures} counts={counts}\n")
        print(f"case {cid}: {status} elapsed={elapsed:.1f}s remaining={remaining}", flush=True)
        if status != 'SUCCESS':
            print(msg, flush=True)
    df = sync_manifest(load_manifest())
    write_pending_diagnostics(df)
    print(df[df['NetworkID'].astype(str)=='ieee30']['Status'].value_counts().to_string())
    return 0 if failures == 0 and timeouts == 0 else 2

if __name__ == '__main__':
    raise SystemExit(main())
